name: Azure Powershell Deployment 

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install PowerShell Module
        run: |
          pwsh -Command "Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser"

      - name: Run PowerShell Deployment Script
        run: |
          pwsh -File ./automate01.ps1
